# 2D Numpy

In [1]:
# Import library

import numpy as np

 Create list a, which contains three nested lists each of equal size.

In [2]:
# Create a list

a = [[11,12,13], [21,22,23], [31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Attribute ndim to obtain the number of axes or dimensions, referred to as the rank.

In [5]:
# Show the numpy array dimensions

A.ndim      # Rows & Columns

2

Attribute shape returns a tuple corresponding to the size or number of each dimension.

In [6]:
# Show the numpy array shape

A.shape

(3, 3)

A tuple is an ordered collection of elements that cannot be changed after it's created.  Tuples are similar to lists in that they can store multiple items of different data types, but unlike lists, tuples are immutable, meaning their elements cannot be added, removed, or modified once the tuple is created.

In [8]:
# Show the numpy array size

A.size      # Gives the total number of elements in the array

9

### Accessing different elements of a Numpy Array

In [9]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [11]:
# Access the element on the second row and third column

A[1,2]

23

In [12]:
# Access the element on the first row and first column

A[0,0]

11

In [19]:
# Access the element on the first row and first and second columns

A[0,[0,1]]
# OR
A[0][0:2]
# OR
A[0, 0:2]

array([11, 12])

In [37]:
# Access the element on the first and second rows and third column

A[0:2,2]

array([1, 1])

### Basic Operations

In [22]:
# Create a numpy array X

X = np.array([[1,0],[0,1]])
X

array([[1, 0],
       [0, 1]])

In [23]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler.

In [24]:
# Multiply Y with 2

Z = 2*Y
Z

array([[4, 2],
       [2, 4]])

We can also perform matrix multiplication with the numpy arrays A and B as follows:

In [28]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [29]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function dot to multiply the arrays together.

In 1D Numpy we use np.multiply but in 2D we use np.dot to multiply.
Also in ID np.dot performs like this (1*2)+(3*4)

In [30]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [31]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [32]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [33]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

### Quiz on 2D Numpy Array

In [38]:
# Consider the following list a, convert it to Numpy Array.

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
# Calculate the numpy array size.

A.size

12

In [41]:
# Access the element on the first row and first and second columns.

A[0,0:2]

array([1, 2])

In [44]:
# Perform matrix multiplication with the numpy arrays A and B.

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
C = np.dot(A,B)
C

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])