# What is Numpy

###### NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices. NumPy stands for Numerical Python and it is an open source project. The array object in NumPy is called ndarray

In [53]:
# import numpy library

import numpy as np 

In [2]:
# Create a numpy array

a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [7]:
# Print each element

print('a[0] =', a[0])
print('a[1] =', a[1])
print('a[2] =', a[2])
print('a[3] =', a[3])
print('a[4] =', a[4])

a[0] = 0
a[1] = 1
a[2] = 2
a[3] = 3
a[4] = 4


In [8]:
# Checking NumPy Version

print(np.__version__)

1.24.3


In [11]:
# Check the type of the array

type(a)

numpy.ndarray

In [ ]:
# Check the type of the values stored in numpy array

a.dtype

### Assign value

In [12]:
# Create numpy array

c = np.array([20,1,2,3,4])
c

array([20,  1,  2,  3,  4])

In [13]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [14]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

### Slicing

In [15]:
# Select the elements from 1 to 3 and assign it to a new numpy array d

d = c[1:4]
d

array([1, 2, 3])

In [20]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [23]:
# We can also define the steps in slicing, like this: [start:end:step value].

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [29]:
# If we don't pass start its considered 0

print(arr[:4])

[1 2 3 4]


In [27]:
# If we don't pass end it considers till the length of array.

print(arr[4:])

[5 6 7]


In [28]:
# If we don't pass step its considered 1

print(arr[1:5:])

[2 3 4 5]


### Assign Value with List

In [51]:
# Create the index list

select = [0,2,3,4]
select

[0, 2, 3, 4]

In [39]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300, 400])

###### This is because previously this was inputted 
c[3:5] = 300, 400
c

resulting this 

       array([100,   1,   2, 300, 400])
here index are 0,     1,   2,  3,   4

For instance, if c contains the elements [apple, banana, cherry, mango, orange], then c[select] would extract [apple, cherry, mango, orange], pertaining to the elements at indexes 0, 2, 3, and 4 in the original list c.

In [40]:
c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

### Other Attributes

In [41]:
# Create a numpy array

a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [43]:
# Get the size of numpy array

a.size

5

The next two attributes will make more sense when we get to higher dimensions but let's review them. The attribute ndim represents the number of array dimensions, or the rank of the array. In this case, one:

In [45]:
# Get the number of dimensions of numpy array

a.ndim     # ndim = no. of dimensions

1

The attribute shape is a tuple of integers indicating the size of the array in each dimension:

A tuple is an ordered collection of elements that cannot be changed after it's created.  Tuples are similar to lists in that they can store multiple items of different data types, but unlike lists, tuples are immutable, meaning their elements cannot be added, removed, or modified once the tuple is created.

In [46]:
# Get the shape/size of numpy array

a.shape

(5,)

In this case, the NumPy array a is one-dimensional (it has one row and five columns), so the output of a.shape is (5,). The comma at the end signifies that it's a tuple containing a single element that is 5

### Numpy Statistical Functions

In [56]:
# Create a numpy array

a = np.array([1,-1,1,-1])
a

array([ 1, -1,  1, -1])

In [57]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [58]:
# Get the standard deviation of numpy array

standard_deviation = a.std()
standard_deviation

1.0

In [59]:
# Create a numpy array

b = np.array([-1,2,3,4,5])
b

array([-1,  2,  3,  4,  5])

In [60]:
# Get the biggest value in the numpy array

max_value = b.max()
max_value

5

In [61]:
# Get the smallest value in the numpy array

smallest_value = b.min()
smallest_value

-1

### Numpy Array Operations

We can use arithmetic operators directly between NumPy arrays

##### Array Addition

In [65]:
# Create a array u

u = np.array([1,0])
u

array([1, 0])

In [66]:
# Create an array v

v = np.array([0,1])
v

array([0, 1])

In [68]:
# Numpy Array Addition & Assigning it to a Variable z

z = np.add(u,v)
z

array([1, 1])

##### Array Subtraction

In [69]:
# Create an array a

a = np.array([10,20,30])
a

array([10, 20, 30])

In [70]:
b = np.array([5,10,15])
b

array([ 5, 10, 15])

In [71]:
# Subtract

c = np.subtract(a,b)
c

array([ 5, 10, 15])

##### Array Multiplication

In [72]:
# Create an array

x = np.array([1,2])
x

array([1, 2])

In [73]:
# Create an array

y = np.array([2,1])
y

array([2, 1])

In [77]:
# Multiply

z = np.multiply(x,y)
z

array([2, 2])

In [80]:
# Scalar Multiplication

zc = 2*z # Here all values of z will be multiplied by 2
zc

array([4, 4])

##### Array Division

In [75]:
# Create an array

a = np.array([10,20,30])
a

array([10, 20, 30])

In [76]:
# Create an array

b = np.array([2,5,10])
b

array([ 2,  5, 10])

In [78]:
# Divide

c = np.divide(a,b)
c

array([5., 4., 3.])

##### Dot Product

In [85]:
# Creating Arrays (X,Y)

X = np.array([1, 2])
Y = np.array([3, 2])

In [86]:
np.dot(X,Y)

7

In [ ]:
# Dot Calculation is like this (1*3) + (2*2)

In [87]:
#Elements of X
print(X[0])
print(X[1])

1
2


In [88]:
#Elements of Y
print(Y[0])
print(Y[1])

3
2


##### Adding Constant to a Numpy Array

In [89]:
# Create a constant to numpy array

u = np.array([1, 2, 3, -1]) 
u

array([ 1,  2,  3, -1])

Now if we add a Constant/Scalar Value with u (1 will be added to every elemt of u)

In [90]:
u + 1

array([2, 3, 4, 0])

##### Mathematical Functions

We can access the value of pi in numpy as follows :

In [91]:
# The value of pi

np.pi

3.141592653589793

In [93]:
# Create the numpy array

x = np.array([0, np.pi/2, np.pi])

In [96]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

### Linspace

A useful function for plotting mathematical functions is linspace. Linspace returns evenly spaced numbers over a specified interval.

numpy.linspace(start, stop, num = int value)

start : start of interval range
    
stop : end of interval range
    
num : Number of samples to generate.

In [101]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2,2, num=5)   

array([-2., -1.,  0.,  1.,  2.])

If we change the parameter num to 9, we get 9 evenly spaced numbers over the interval from -2 to 2:

In [102]:
# Makeup a numpy array within [-2, 2] and 9 elements

np.linspace(-2,2, num=9)   

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [104]:
# Make a numpy array within [5, 4] and 6 elements

np.linspace(5,4, num = 6)

array([5. , 4.8, 4.6, 4.4, 4.2, 4. ])

### Iterating 1-D Arrays

One Dimensional Array

Iterating means going through elements one by one.

###### If we execute the numpy array, we get in the array format

In [109]:
arr1 = np.array([1,2,3])
print(arr1)
type(arr1)

[1 2 3]


numpy.ndarray

###### But if you want to result in the form of the list, then you can use for loop:

In [114]:
for x in arr1:
    print(x)
type(x)                  # Its a list

1
2
3


numpy.int32

### Quiz on 1D Numpy Array

In [116]:
# Implement the following vector subtraction in numpy: u-v

u = np.array([1, 0])
v = np.array([0, 1])
np.subtract(u,v)

array([ 1, -1])

In [118]:
# Multiply the numpy array z with -2:

z = np.array([2, 4])
a = -2*z
a

array([-4, -8])

In [119]:
# Consider the list [1, 2, 3, 4, 5] and [1, 0, 1, 0, 1]. Cast both lists to a numpy array then multiply them together:

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])

c = np.multiply(a,b)
c

array([1, 0, 3, 0, 5])

In [121]:
# Convert the list [1, 2, 3, 4, 5] and [6, 7, 8, 9, 10] to numpy arrays arr1 and arr2. Then find the even and odd numbers from arr1 and arr2.

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

even_arr1 = arr1[1:5:2]
print('Even No. in aar1 =', even_arr1)

odd_arr1 = arr1[0:5:2]
print('Odd No. in arr1 = ', odd_arr1)

even_arr2 = arr2[0:5:2]
print('Even No. in arr2 =', even_arr2)

odd_arr2 = arr2[1:5:2]
print('Odd No. in arr2 =', odd_arr2)

Even No. in aar1 = [2 4]
Odd No. in arr1 =  [1 3 5]
Even No. in arr2 = [ 6  8 10]
Odd No. in arr2 = [7 9]
